# .github/workflows/metrics.yml
name: Metrics
on:
  schedule:
    # Runs every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # This requires a Personal Access Token (PAT) with repo and user scope.
          # Create one here: https://github.com/settings/tokens/new
          # And add it to your repository secrets with the name METRICS_TOKEN
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Replace with your GitHub username and timezone
          user: Dheeraj22
          config_timezone: America/New_York

          # Action options
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_lines: yes
          plugin_people: yes
          plugin_people_types: followers, following
